server:
  port: 1212


spring:
  datasource:
    name: mysql_test
    #-------------- start ----------------# (1)
    master:
      #基本属性--注意，这里的为【jdbcurl】-- 默认使用HikariPool作为数据库连接池
      jdbcurl: jdbc:mysql://127.0.0.1:3306/admin?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    slave:
      #基本属性--注意，这里为 【url】-- 使用 druid 作为数据库连接池
      url: jdbc:mysql://127.0.0.1:3306/admin?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
    read: get,select,query,find
    write: add,update,delete,remove,insert,save,modify
    #-------------- end ----------------#
    ###############  druid相关配置  ####################
    druid:
      ###############  监控统计拦截的filters  #####################
      filters: stat
      ############  配置初始化大小/最小/最大  ####################
      initial-size: 1
      min-idle: 1
      max-active: 20
      ###########   获取连接等待超时时间
      max-wait: 60000
      ###########   间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      ###########   一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      ###########   打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
## 手动ACK 不开启自动ACK模式,目的是防止报错后未正确处理消息丢失 默认 为 none
    listener:
      simple:
        acknowledge-mode: manual
  thymeleaf:
    cache: false  #禁用 thymeleaf 缓存
  servlet:
    multipart:
      enabled: true 				#是否支持批量上传
      location:
      max-file-size: 1048576   		#上传文件最大为 1M 
      max-request-size: 10485760    #上传请求最大为 10M（默认值10M 根据自身业务自行控制即可）
      file-size-threshold: 0        #文件大小阈值，当大于这个阈值时将写入到磁盘，否则存在内存中，（默认值0 一般情况下不用特意修改）
      resolve-lazily: false         #判断是否要延迟解析文件（相当于懒加载，一般情况下不用特意修改）
#  resources:
#    static-locations: classpath:/resources/,classpath:/static/,file:${web.upload-path}
#web:
#  upload-path: ./chapter/src/main/resources/static/image/ 
# 配置那个路径下日志不打印
#logging:   
#  level:
#    ...   

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hytx.jcxfd.model

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
    
